#!/usr/bin/env bash
# project-planner.sh — Auto-detect new items in GitHub Project #2 and create plan issues
#
# Usage:
#   ./scripts/project-planner.sh              # run once, check all pending
#   ./scripts/project-planner.sh --dry-run    # preview without creating issues
#   ./scripts/project-planner.sh --issue 76   # plan a specific issue number

set -euo pipefail

OWNER="allday9z"
PROJECT_NUM=2
REPO="allday9z/m2developer.com"
DRY_RUN=false
TARGET_ISSUE=""

# Parse args
for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
    --issue) TARGET_ISSUE="${2:-}" ;;
    --issue=*) TARGET_ISSUE="${arg#*=}" ;;
  esac
done

echo "🔍 Oracle Project Planner — $(date '+%Y-%m-%d %H:%M %Z')"
echo "📋 Watching: Project #${PROJECT_NUM} (${OWNER})"
echo ""

# ── 1. Fetch all non-Done items from Project #2 ────────────────────────────
ITEMS_JSON=$(gh project item-list $PROJECT_NUM --owner "$OWNER" --format json --limit 100 2>/dev/null)

if [ -z "$ITEMS_JSON" ]; then
  echo "❌ Could not fetch project items. Check gh auth status."
  exit 1
fi

# Filter: not Done, is from m2developer.com repo, is an Issue
PENDING=$(ITEMS_JSON_DATA="$ITEMS_JSON" python3 - <<'PYEOF'
import json, sys, os

data = json.loads(os.environ['ITEMS_JSON_DATA'])
repo_filter = "allday9z/m2developer.com"
done_statuses = {"Done", "Closed", "Complete", "Completed"}

results = []
for item in data.get("items", []):
    status = item.get("status", "")
    repo = item.get("repository", "")
    content = item.get("content", {})

    if status in done_statuses:
        continue
    if repo_filter not in repo:
        continue
    if content.get("type") != "Issue":
        continue

    results.append({
        "number": content["number"],
        "title": content["title"],
        "status": status or "No Status",
        "url": content["url"],
    })

print(json.dumps(results))
PYEOF
)

TOTAL=$(echo "$PENDING" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")

if [ "$TOTAL" -eq 0 ]; then
  echo "✅ No pending items — all tasks are Done."
  exit 0
fi

echo "📌 Found ${TOTAL} pending item(s):"
echo "$PENDING" | python3 -c "
import json,sys
for i in json.load(sys.stdin):
    print(f\"  #{i['number']:>4}  [{i['status']:15}]  {i['title'][:60]}\")
"
echo ""

# ── 2. For each item, check if a plan already exists ──────────────────────
PLANNED=0
CREATED=0

while IFS= read -r item; do
  ISSUE_NUM=$(echo "$item" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['number'])")
  ISSUE_TITLE=$(echo "$item" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['title'])")
  ISSUE_STATUS=$(echo "$item" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['status'])")

  # Skip if --issue flag is set and this isn't the target
  if [ -n "$TARGET_ISSUE" ] && [ "$ISSUE_NUM" != "$TARGET_ISSUE" ]; then
    continue
  fi

  # Check if plan issue already exists
  PLAN_COUNT=$(gh issue list \
    --repo "$REPO" \
    --search "plan: #${ISSUE_NUM} in:title" \
    --state open \
    --json number \
    --jq 'length' 2>/dev/null || echo "0")

  if [ "$PLAN_COUNT" -gt 0 ]; then
    echo "⏭️  #${ISSUE_NUM} already has a plan — skipping"
    PLANNED=$((PLANNED + 1))
    continue
  fi

  echo "📝 Creating plan for #${ISSUE_NUM}: ${ISSUE_TITLE}"

  if [ "$DRY_RUN" = true ]; then
    echo "   [DRY RUN] Would create: 'plan: ${ISSUE_TITLE} (#${ISSUE_NUM})'"
    continue
  fi

  # ── 3. Read original issue body ──────────────────────────────────────
  ISSUE_BODY=$(gh issue view "$ISSUE_NUM" --repo "$REPO" --json body --jq '.body' 2>/dev/null || echo "")

  # ── 4. Create plan issue ─────────────────────────────────────────────
  PLAN_URL=$(gh issue create \
    --repo "$REPO" \
    --title "plan: ${ISSUE_TITLE} (#${ISSUE_NUM})" \
    --label "plan" \
    --body "## Implementation Plan

**Source Issue**: #${ISSUE_NUM} — ${ISSUE_TITLE}
**Status**: ${ISSUE_STATUS}
**Auto-generated**: $(date '+%Y-%m-%d %H:%M %Z')

---

## Context

$([ -n "$ISSUE_BODY" ] && echo "$ISSUE_BODY" | head -20 || echo "_No description provided._")

---

## Analysis Checklist

- [ ] Read all related files and understand current state
- [ ] Identify all affected components/routes/APIs
- [ ] Check for breaking changes or migration needed
- [ ] Review similar patterns in codebase

## Implementation Steps

- [ ] Step 1: _(define after analysis)_
- [ ] Step 2:
- [ ] Step 3:

## Files to Modify

| File | Change |
|------|--------|
| | |

## Testing

- [ ] \`bun run lint\` — 0 errors
- [ ] \`bun run build\` — clean build
- [ ] Manual test in browser
- [ ] Mobile responsive check

## Definition of Done

- [ ] PR created and passes CI
- [ ] Original issue #${ISSUE_NUM} closed or linked

---
*🤖 Auto-generated by Oracle Project Planner — run \`nnn #${ISSUE_NUM}\` to fill in AI-powered details*" \
    2>/dev/null)
  PLAN_ISSUE=$(echo "$PLAN_URL" | grep -o '[0-9]*$')

  if [ -n "$PLAN_ISSUE" ]; then
    # Add plan issue to Project #2
    gh project item-add $PROJECT_NUM \
      --owner "$OWNER" \
      --url "https://github.com/${REPO}/issues/${PLAN_ISSUE}" 2>/dev/null || true

    echo "   ✅ Created plan #${PLAN_ISSUE} → https://github.com/${REPO}/issues/${PLAN_ISSUE}"
    CREATED=$((CREATED + 1))
  else
    echo "   ❌ Failed to create plan for #${ISSUE_NUM}"
  fi

done < <(echo "$PENDING" | python3 -c "
import json,sys
for item in json.load(sys.stdin):
    print(json.dumps(item))
")

echo ""
echo "─────────────────────────────────────"
echo "📊 Summary: ${CREATED} plan(s) created, ${PLANNED} already planned"
echo "─────────────────────────────────────"
